// Generated by gencpp from file rmi/MoveArmResponse.msg
// DO NOT EDIT!


#ifndef RMI_MESSAGE_MOVEARMRESPONSE_H
#define RMI_MESSAGE_MOVEARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmi
{
template <class ContainerAllocator>
struct MoveArmResponse_
{
  typedef MoveArmResponse_<ContainerAllocator> Type;

  MoveArmResponse_()
    : success(false)  {
    }
  MoveArmResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rmi::MoveArmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmi::MoveArmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmResponse_

typedef ::rmi::MoveArmResponse_<std::allocator<void> > MoveArmResponse;

typedef boost::shared_ptr< ::rmi::MoveArmResponse > MoveArmResponsePtr;
typedef boost::shared_ptr< ::rmi::MoveArmResponse const> MoveArmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmi::MoveArmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmi::MoveArmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmi::MoveArmResponse_<ContainerAllocator1> & lhs, const ::rmi::MoveArmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmi::MoveArmResponse_<ContainerAllocator1> & lhs, const ::rmi::MoveArmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rmi::MoveArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmi::MoveArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmi::MoveArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmi::MoveArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmi::MoveArmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmi::MoveArmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmi::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rmi::MoveArmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rmi::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmi/MoveArmResponse";
  }

  static const char* value(const ::rmi::MoveArmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmi::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::rmi::MoveArmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmi::MoveArmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmi::MoveArmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmi::MoveArmResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMI_MESSAGE_MOVEARMRESPONSE_H
