// Generated by gencpp from file rmi/MoveArm.msg
// DO NOT EDIT!


#ifndef RMI_MESSAGE_MOVEARM_H
#define RMI_MESSAGE_MOVEARM_H

#include <ros/service_traits.h>


#include <rmi/MoveArmRequest.h>
#include <rmi/MoveArmResponse.h>


namespace rmi
{

struct MoveArm
{

typedef MoveArmRequest Request;
typedef MoveArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveArm
} // namespace rmi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmi::MoveArm > {
  static const char* value()
  {
    return "74ba88dd7a232cebfc2c0ee0e397f0fc";
  }

  static const char* value(const ::rmi::MoveArm&) { return value(); }
};

template<>
struct DataType< ::rmi::MoveArm > {
  static const char* value()
  {
    return "rmi/MoveArm";
  }

  static const char* value(const ::rmi::MoveArm&) { return value(); }
};


// service_traits::MD5Sum< ::rmi::MoveArmRequest> should match
// service_traits::MD5Sum< ::rmi::MoveArm >
template<>
struct MD5Sum< ::rmi::MoveArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmi::MoveArm >::value();
  }
  static const char* value(const ::rmi::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmi::MoveArmRequest> should match
// service_traits::DataType< ::rmi::MoveArm >
template<>
struct DataType< ::rmi::MoveArmRequest>
{
  static const char* value()
  {
    return DataType< ::rmi::MoveArm >::value();
  }
  static const char* value(const ::rmi::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmi::MoveArmResponse> should match
// service_traits::MD5Sum< ::rmi::MoveArm >
template<>
struct MD5Sum< ::rmi::MoveArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmi::MoveArm >::value();
  }
  static const char* value(const ::rmi::MoveArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmi::MoveArmResponse> should match
// service_traits::DataType< ::rmi::MoveArm >
template<>
struct DataType< ::rmi::MoveArmResponse>
{
  static const char* value()
  {
    return DataType< ::rmi::MoveArm >::value();
  }
  static const char* value(const ::rmi::MoveArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMI_MESSAGE_MOVEARM_H
